repositories:
  - name: parity
    url: https://paritytech.github.io/helm-charts/

helmDefaults:
  createNamespace: false
  waitForJobs: true

releases:
  - name: testnet-manager
    namespace: wococo
    chart: parity/testnet-manager
    version: # empty value is latest
    values:
      - ./values-testnet-manager.yml
      - configmap:
          RELAY_CHAIN_RPC_URL: "ws://localwococo-bootnode.wococo:9944"
          RPC_NODE_URL_PATTERN: "NODE_NAME.wococo:9944"
          RELAY_CHAIN_CONSENSUS: pos

  - name: localwococo-bootnode
    namespace: wococo
    chart: parity/node
    version: &node_version 5.1.7
    values:
      - ./values-localwococo-bootnode.yaml

  - name: localwococo-validator-a
    namespace: wococo
    chart: parity/node
    version: *node_version
    values:
      - ./values-localwococo-bootnode.yaml
      - node:
          replicas: 2
          keys: []
