repositories:
  - name: parity
    url: https://paritytech.github.io/helm-charts/

helmDefaults:
  createNamespace: true
  waitForJobs: true

releases:
## testnet-manager ##
  - name: testnet-manager
    namespace: rococo
    chart: parity/testnet-manager
    version: 1.1.1
    values:
      - ./values-testnet-manager.yml

## relay chain Rococo ##
  - name: localrococo-validator-alice
    namespace: rococo
    chart: parity/node
    version: 2.11.4
    values:
      - ./values-localrococo-validator-a.yaml
      - node:
          replicas: 1
          flags:
            - "--alice"
            - "--unsafe-rpc-external"
            - "--unsafe-ws-external"
            - "--rpc-methods=unsafe"
            - "--rpc-cors=all"
        extraLabels:
          validatorAccount: "5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY" # Alice address

  - name: localrococo-validator-bob
    namespace: rococo
    chart: parity/node
    version: 2.11.4
    values:
      - ./values-localrococo-validator-a.yaml
      - node:
          replicas: 1
          flags:
            - "--bob"
            - "--unsafe-rpc-external"
            - "--unsafe-ws-external"
            - "--rpc-methods=unsafe"
            - "--rpc-cors=all"
        extraLabels:
          validatorAccount: "5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc" # Alice address
  - name: localrococo-validator-a
    namespace: rococo
    chart: parity/node
    version: 2.11.4
    values:
      - ./values-localrococo-validator-a.yaml

## Para chain Shell ##
  - name: localrococo-shell-collator
    namespace: rococo
    chart: parity/node
    version: 2.11.4
    values:
      - values-shell-collator.yaml

## Para chain Statemint ##
  - name: localrococo-statemint-alice
    namespace: rococo
    chart: parity/node
    version: 2.11.4
    values:
      - values-statemint-collator.yaml
      - node:
          flags:
            - "--unsafe-rpc-external"
            - "--unsafe-ws-external"
            - "--rpc-methods=unsafe"
            - "--rpc-cors=all"
            - "--alice"
        extraLabels:
          paraId: "1003"
          ss58Format: "0"
          collatorAccount: "15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5" # Alice Polkadot address
  - name: localrococo-statemint-bob
    namespace: rococo
    chart: parity/node
    version: 2.11.4
    values:
      - values-statemint-collator.yaml
      - node:
          flags:
            - "--unsafe-rpc-external"
            - "--unsafe-ws-external"
            - "--rpc-methods=unsafe"
            - "--rpc-cors=all"
            - "--bob"
        extraLabels:
          paraId: "1003"
          ss58Format: "0"
          collatorAccount: "14E5nqKAp3oAJcmzgZhUD2RcptBeUBScxKHgJKU4HPNcKVf3" # Bob Polkadot address
  - name: localrococo-statemint-c
    namespace: rococo
    chart: parity/node
    version: 2.11.4
    values:
      - values-statemint-collator.yaml

## Para chain Moonbase ##
  - name: localrococo-moonbase-alice
    namespace: rococo
    chart: parity/node
    version: 2.11.4
    values:
      - values-moonbase-collator.yml
      - node:
          replicas: 1
          flags:
            - "--unsafe-rpc-external"
            - "--unsafe-ws-external"
            - "--rpc-methods=unsafe"
            - "--rpc-cors=all"
            - "--allow-private-ipv4"
            - "--alice"
        extraLabels:
          paraId: "1001"
          collatorAccount: "0xf24ff3a9cf04c71dbc94d0b566f7a27b94566cac"
  # collators
  - name: localrococo-moonbase-collator
    namespace: rococo
    chart: parity/node
    version: 2.11.4
    values:
      - values-moonbase-collator.yml

## Para chain Tick ##
  - name: localrococo-tick-collator
    namespace: rococo
    chart: parity/node
    version: 2.11.4
    values:
      - values-tick-collator.yml

#### WOCOCO
  - name: testnet-manager
    namespace: wococo
    chart: parity/testnet-manager
    version: 1.1.1
    values:
      - ./values-testnet-manager.yml
      - configmap:
          WS_ENDPOINT: "ws://localwococo-bootnode.wococo:9944"
          NODE_HTTP_PATTERN: "http://NODE_NAME.wococo:9933"
          NODE_WS_PATTERN: "ws://NODE_NAME.wococo:9944"
          TESTNET_MANAGER_CONSENSUS: pos

  - name: localwococo-bootnode
    namespace: wococo
    chart: parity/node
    version: 3.5.0
    values:
      - ./values-localwococo-bootnode.yaml

  - name: localwococo-validator-a
    namespace: wococo
    chart: parity/node
    version: 3.5.0
    values:
      - ./values-localwococo-bootnode.yaml
      - node:
          replicas: 2
          keys: []
