repositories:
  - name: parity
    url: https://paritytech.github.io/helm-charts/

helmDefaults:
  createNamespace: false
  waitForJobs: true

releases:
## testnet-manager ##
  - name: testnet-manager
    namespace: rococo
    chart: parity/testnet-manager
    version: # empty value is latest
    values:
      - ./values-testnet-manager.yml

## relay chain Rococo ##
  - name: localrococo-bootnode
    namespace: rococo
    chart: parity/node
    version: &node_version 5.1.7
    values:
      - ./values-localrococo-bootnode.yaml
      - node:
          flags:
            - "--alice"
        extraLabels:
          validatorAccount: "5GNJqTPyNqANBkUVMN1LPPrxXnFouWXoe2wNSmmEoLctxiZY" # Alice address

  - name: localrococo-bootnode-bob
    namespace: rococo
    chart: parity/node
    version: *node_version
    values:
      - ./values-localrococo-bootnode.yaml
      - node:
          flags:
            - "--bob"
        extraLabels:
          validatorAccount: "5HpG9w8EBLe5XCrbczpwq5TSXvedjrBGCwqxK1iQ7qUsSWFc" # Bob address

  - name: localrococo-validator-a
    namespace: rococo
    chart: parity/node
    version: *node_version
    values:
      - ./values-localrococo-bootnode.yaml
      - node:
          replicas: 1
      - node:
          keys:
            - type: gran
              scheme: "ed25519"
              seed: "test test test test test test test test test test test junk"
              extraDerivation: "//validator//${HOSTNAME}"
            - type: babe
              scheme: "sr25519"
              seed: "test test test test test test test test test test test junk"
              extraDerivation: "//validator//${HOSTNAME}"

## Para chain Shell ##
  - name: localrococo-shell-collator
    namespace: rococo
    chart: parity/node
    version: *node_version
    values:
      - values-shell-collator.yaml

# Para chain Statemint ##
  - name: localrococo-statemint-alice
    namespace: rococo
    chart: parity/node
    version: *node_version
    values:
      - values-statemint-collator.yaml
      - node:
          flags:
            - "--alice"
        extraLabels:
          paraId: "1003"
          ss58Format: "0"
          collatorAccount: "15oF4uVJwmo4TdGW7VfQxNLavjCXviqxT9S1MgbjMNHr6Sp5" # Alice Polkadot address
  - name: localrococo-statemint-bob
    namespace: rococo
    chart: parity/node
    version: *node_version
    values:
      - values-statemint-collator.yaml
      - node:
          flags:
            - "--bob"
        extraLabels:
          paraId: "1003"
          ss58Format: "0"
          collatorAccount: "14E5nqKAp3oAJcmzgZhUD2RcptBeUBScxKHgJKU4HPNcKVf3" # Bob Polkadot address
  - name: localrococo-statemint-a
    namespace: rococo
    chart: parity/node
    version: *node_version
    values:
      - values-statemint-collator.yaml
      - node:
          keys:
            - type: aura
              scheme: "sr25519"
              seed: "test test test test test test test test test test test junk"
              extraDerivation: "//collator//${HOSTNAME}"
## Para chain Moonbase ##
  - name: localrococo-moonbase-alice
    namespace: rococo
    chart: parity/node
    version: *node_version
    values:
      - values-moonbase-collator.yml
      - node:
          flags:
            - "--allow-private-ipv4"
            - "--alice"
        extraLabels:
          paraId: "1001"
          collatorAccount: "0xf24ff3a9cf04c71dbc94d0b566f7a27b94566cac"
  # collators
  - name: localrococo-moonbase-collator
    namespace: rococo
    chart: parity/node
    version: *node_version
    values:
      - values-moonbase-collator.yml

## Para chain Tick ##
  - name: localrococo-tick-collator
    namespace: rococo
    chart: parity/node
    version: *node_version
    values:
      - values-tick-collator.yml
