image:
  # also update version in kube-setup/validators-chainspec.yml
  repository: moonbeamfoundation/moonbeam
  tag: latest
  pullPolicy: Always

initContainer:
  debug: true

node:
  chainData: &chainData
    volumeSize: 2Gi
    storageClass: "standard"
  chainKeystore: &chainKeystore
    mountInMemory:
      enabled: true
      sizeLimit: 10Mi
  chain: moonbase
  role: collator
  replicas: 1
  command: "/moonbeam/moonbeam"
  # kube-setup/validators-chainspec.yml
  forceDownloadChainspec: true
  customChainspecUrl:  "http://chainspec.rococo/moonbase.json"
  customChainspecPath: "/chain-data/moonbase.json"
  isParachain: true
  collatorRelayChain:
    customChainspecUrl: "http://chainspec.rococo/rococo-local.json"
    chainData: *chainData
    chainKeystore: *chainKeystore
  persistGeneratedNodeKey: true
  allowUnsafeRpcMethods: true
  # To be removed once https://github.com/moonbeam-foundation/moonbeam/pull/2359
  # is included in release
  legacyRpcFlags: true
  flags:
    - "--allow-private-ipv4"

extraLabels:
  paraId: "1001"
