image:
  # also update version in kube-setup/chainspec.yml
  repository: parity/polkadot-collator
  tag: latest
  pullPolicy: IfNotPresent

initContainer:
  debug: true

node:
  dataVolumeSize: 2Gi
  chain: shell
  role: collator
  replicas: 1
  command: "/usr/local/bin/polkadot-collator"
  # manifests/chainspec.yml
  forceDownloadChainspec: true
  customChainspecUrl:  "http://chainspec.rococo/shell.json"
  collator:
    isParachain: true
    # manifests/chainspec.yml
    relayChainCustomChainspecUrl: "http://chainspec.rococo/rococo-local.json"
  persistGeneratedNodeKey: true
  perNodeServices:
    relayP2pService:
      enabled: true
      type: NodePort
    paraP2pService:
      enabled: true
      type: NodePort
  flags:
    - "--unsafe-rpc-external"
    - "--unsafe-ws-external"
    - "--rpc-methods=safe"
    - "--rpc-cors=all"

extraLabels:
  paraId: "1000"

storageClass: "standard"
