image:
  # also update version in kube-setup/validators-chainspec.yml
  repository: parity/polkadot
  tag: latest
  pullPolicy: Always

initContainer:
  debug: true

node:
  chain: rococo-local
  role: authority
  replicas: 1
  chainData:
    pruning: 1000
    volumeSize: 2Gi
    storageClass: "standard"
  chainKeystore:
    mountInMemory:
      enabled: true
      sizeLimit: 10Mi
  podManagementPolicy: Parallel
  allowUnsafeRpcMethods: true
  # kube-setup/validators-chainspec.yml
  customChainspecUrl: http://chainspec.rococo/rococo-local.json
  forceDownloadChainspec: true

extraInitContainers:
  - name: dump-session-keys
    image: docker.io/paritytech/substrate-session-keys-grabber:d17032f1-20221202
    args: ["/keystore"]
    volumeMounts:
      - mountPath: /keystore
        name: chain-keystore