image:
  # also update version in manifests/chainspec.yml
  repository: purestake/moonbeam
  tag: latest
  pullPolicy: IfNotPresent

initContainer:
  debug: true

node:
  chainData: &chainData
    volumeSize: 2Gi
    storageClass: "standard"
  chainKeystore: &chainKeystore
    mountInMemory:
      enabled: true
      sizeLimit: 10Mi
  chain: moonbase
  role: collator
  replicas: 1
  command: "/moonbeam/moonbeam"
  # manifests/chainspec.yml
  forceDownloadChainspec: true
  customChainspecUrl:  "http://chainspec.rococo/moonbase.json"
  customChainspecPath: "/chain-data/moonbase.json"
  isParachain: true
  collatorRelayChain:
    customChainspecUrl: "http://chainspec.rococo/rococo-local.json"
    chainData: *chainData
    chainKeystore: *chainKeystore
  persistGeneratedNodeKey: true
  allowUnsafeRpcMethods: true
  flags:
    - "--allow-private-ipv4"

extraLabels:
  paraId: "1001"
