image:
  # also update version in manifests/chainspec.yml
  repository: parity/polkadot-collator
  tag: latest
  pullPolicy: IfNotPresent

initContainer:
  debug: true

node:
  chainData: &chainData
    volumeSize: 2Gi
    storageClass: "standard"
  chainKeystore: &chainKeystore
    mountInMemory:
      enabled: true
      sizeLimit: 10Mi
  chain: tick
  role: collator
  replicas: 2
  command: "/usr/local/bin/polkadot-collator"
  # manifests/chainspec.yml
  forceDownloadChainspec: true
  customChainspecUrl:  "http://chainspec.rococo/tick.json"
  isParachain: true
  collatorRelayChain:
    customChainspecUrl: "http://chainspec.rococo/rococo-local.json"
    chainData: *chainData
    chainKeystore: *chainKeystore
  persistGeneratedNodeKey: true
  allowUnsafeRpcMethods: true
  flags:
    - "--allow-private-ipv4"

extraLabels:
  paraId: "1002"

