image:
  # also update version in manifests/chainspec.yml
  repository: parity/polkadot
  tag: latest
  pullPolicy: IfNotPresent

initContainer:
  debug: true

node:
  chain: rococo-local
  role: authority
  replicas: 1
  chainData:
    pruning: 1000
    volumeSize: 2Gi
    storageClass: "standard"
  chainKeystore:
    mountInMemory:
      enabled: true
      sizeLimit: 10Mi
  podManagementPolicy: Parallel
  allowUnsafeRpcMethods: true
  # kube-setup/chainspec.yml
  customChainspecUrl: http://chainspec.rococo/rococo-local.json
  forceDownloadChainspec: true
