image:
  # also update version in kube-setup/chainspec.yml
  repository: parity/polkadot-collator
  tag: latest
  pullPolicy: IfNotPresent

initContainer:
  debug: true

node:
  chainData: &chainData
    volumeSize: 2Gi
    storageClass: "standard"
  chainKeystore: &chainKeystore
    mountInMemory:
      enabled: true
      sizeLimit: 10Mi
  chain: shell
  role: collator
  replicas: 1
  command: "/usr/local/bin/polkadot-collator"
  # manifests/chainspec.yml
  forceDownloadChainspec: true
  customChainspecUrl:  "http://chainspec.rococo/shell.json"
  isParachain: true
  collatorRelayChain:
    customChainspecUrl: "http://chainspec.rococo/rococo-local.json"
    chainData: *chainData
    chainKeystore: *chainKeystore
  persistGeneratedNodeKey: true
  flags:
    - "--unsafe-pruning"

extraLabels:
  paraId: "1000"
