apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: testnet-manager
build:
  artifacts:
    - image: localhost/testnet-manager
      docker: {}
  local:
    useBuildkit: true
    push: false
deploy:
  helm:
    releases:
    - name: testnet-manager
      namespace: rococo
      repo: https://paritytech.github.io/helm-charts/
      remoteChart: testnet-manager
      upgradeOnChange: true
      valuesFiles:
        - local-kubernetes/charts/values-testnet-manager.yml
portForward:
- resourceType: service
  resourceName: testnet-manager
  namespace: rococo
  port: 80
  localPort: 8080
- resourceType: service
  resourceName: testnet-manager-task-scheduler
  namespace: rococo
  port: 80
  localPort: 8081
