## nginx which hosts `polkadot build-spec` command output
apiVersion: v1
kind: Service
metadata:
  name: chainspec
  labels:
    run: chainspec
  namespace: rococo
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: chainspec
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chainspec
  namespace: rococo
spec:
  selector:
    matchLabels:
      run: chainspec
  replicas: 1
  template:
    metadata:
      labels:
        run: chainspec
    spec:
      volumes:
      - name: dir
        emptyDir: {}
      containers:
      - name: chainspec
        image: nginx:stable
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: dir
          mountPath: /usr/share/nginx/html
      initContainers:
      - name: create-chainspec-rococolocal
        image: parity/polkadot:latest
        imagePullPolicy: IfNotPresent
        command: [ "/bin/sh" ]
        args:
          - -c
          - /usr/bin/polkadot build-spec --chain rococo-local --disable-default-bootnode --raw  > /dir/rococo-local.json
        volumeMounts:
        - name: dir
          mountPath: /dir
      - name: create-chainspec-statemint
        image: parity/polkadot-parachain:latest
        command: [ "/bin/sh" ]
        args:
          - -c
          - >
            set -xe;
            polkadot-parachain build-spec --chain asset-hub-westend-local --disable-default-bootnode > /dir/statemint-plain.json;
            sed 's/"para_id": 1000/"para_id": 1003/' -i /dir/statemint-plain.json;
            sed 's/"parachainId": 1000/"parachainId": 1003/' -i /dir/statemint-plain.json;
            echo "make 5GmS1wtCfR4tK5SSgnZbVT4kYw5W8NmxmijcsxCQE6oLW6A8 (DERIVATION_ROOT_SEED) rich";
            sed 's/5CRmqmsiNFExV6VbdmPJViVxrWmkaXXvBrSX8oqBT8R9vmWk/5GmS1wtCfR4tK5SSgnZbVT4kYw5W8NmxmijcsxCQE6oLW6A8/' -i /dir/statemint-plain.json;
            polkadot-parachain build-spec --chain /dir/statemint-plain.json --disable-default-bootnode --raw  > /dir/statemint.json;
        volumeMounts:
        - name: dir
          mountPath: /dir
      - name: create-chainspec-tick
        image: parity/polkadot-parachain:latest
        command: [ "/bin/sh" ]
        args:
          - -c
          - >
            set -xe;
            polkadot-parachain build-spec --chain staging > /dir/tick-dev-plain.json;
            sed 's/Staging Testnet/Tick/' -i /dir/tick-dev-plain.json;
            sed 's/staging_testnet/tick/' -i /dir/tick-dev-plain.json;
            sed 's/"relay_chain": "westend"/"relay_chain": "rococo"/' -i /dir/tick-dev-plain.json;
            sed 's/"para_id": 1000/"para_id": 1002/' -i /dir/tick-dev-plain.json;
            sed 's/"parachainId": 1000/"parachainId": 1002/' -i /dir/tick-dev-plain.json;
            sed 's/5FeyRQmjtdHoPH56ASFW76AJEP1yaQC1K9aEMvJTF9nzt9S9/5G4849RFENXy6xMyXDZB2aEBs8tNaVsjjkWDQao3CewdFyZm/' -i /dir/tick-dev-plain.json;
            sed 's/5FvikUCHt9tQa98Auqa6mXGuhs3zBs6VsBv1JqfqziS252Ja/5Fnv5ZJJNhxQdQJm43pcGJSQigoZxqgJSoha8SVpXbJ8iknD/' -i /dir/tick-dev-plain.json;
            sed 's/5GsHTRwWBzPixrft2FVYG7SvjFjj3jsBB1Kx6zhEDzgZvczS/5HGJty2oZ8nv1x3JPNtFps11Xw787ZwPdzixX1TtuhbC5Fhq/' -i /dir/tick-dev-plain.json;
            polkadot-parachain build-spec --chain /dir/tick-dev-plain.json --raw > /dir/tick.json;
        # 5G4849RFENXy6xMyXDZB2aEBs8tNaVsjjkWDQao3CewdFyZm - DERIVATION_ROOT_SEED//Alice
        # 5Fnv5ZJJNhxQdQJm43pcGJSQigoZxqgJSoha8SVpXbJ8iknD - DERIVATION_ROOT_SEED//collator//local-rococo-tick-collator-node-0
        # 5HGJty2oZ8nv1x3JPNtFps11Xw787ZwPdzixX1TtuhbC5Fhq - DERIVATION_ROOT_SEED//collator//local-rococo-tick-collator-node-1
        volumeMounts:
          - name: dir
            mountPath: /dir
        securityContext:
          runAsUser: 0
